let animes_list = ['ajin',
'akame ga kill',
'akatsuki no yona',
'angel bits',
'anohana',
'another',
'ansatsu kyoujitsu',
'ao haru ride',
'ao no exorcist',
'asobi asobase',
'atack on titan',
'bakemonogatari',
'bakuman',
'banana fish',
'black clover',
'bleach' ,
'blend s',
'boku dake ga inai machi',
'boku no hero',
'bokutachi we benkyou',
'boruto',
'bungou stray dogs',
'cavaleiros do zodiaco',
'Charlotte',
'Citrus',
'Code Geas',
'Darling in the franxx',
'Death note',
'Digimon',
'Domestic kanojo',
'Dororo',
'Dragon ball',
'Dungeon ni deai',
'Elfen lied',
'Eromanga sensei',
'Fairy tail',
'Fate',
'Fruits basket',
'Fullmetal alchemist brottherhood',
'Goblin slayer',
'Golden time',
'Gotoubun no hanayome',
'Haikyuu',
'High scool sxs',
'Hunter x Hunter',
'Hyouka',
'Isekai wa smartphone',
'Jojo',
'K-on',
'Kaguya sama love is war',
'Kenja no mago',
'Kill la kill',
'Kimetsu no yaiba',
'Kobayashi san chi no maid dragon',
'Konosuba',
'Kuroko no basket',
'Made in abyss',
'Magi',
'Mahouka koukou no rettousei',
'Mahoutsukai no yome',
'Masamune revenge',
'Mob psycho 100',
'Monster',
'No game no life',
'Nanatsu no taizai', 
'Naruto',
'Naruto shippuden',
'Nisekoi',
'Noragami',
'One piece',
'One punch man',
'Overlord',
'Owari no seraph',
'Rakudai kishi',
'Re:zero',
'Reborn',
'Relife',
'Saiki',
'Sailor moon',
'Sakura card captors', 
'Sakurasou',
'Sangatsu no lion',
'Seishou buta yarou bunny girl senpai',
'Shokugeki no souma',
'Sora yori',
'Soul eater',
'Steins gate',
'Sword art online',
'Tater no yuusha',
'Tengen toppa',
'The promissed neverland',
'Tokyo ghoul',
'Toradora',
'Violet evergarden',
'Youjo senki',
'Youkoso jitsuryoku',
'Yu-gioh',
]

